[package]
name = "LegacyCoinDeployerV2"
version = "1.0.0"
authors = []

[addresses]
bapt_framework = "0xd0ec361a55b327913690b2851cec05f1e017ec6c647689cae051644f667a1ddb" 

[dev-addresses]

[dependencies]
AptosFramework = {git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "mainnet"}
BaptSwap = {local = "./packages/BaptSwap"}
BaptswapV2 = {local = "./packages/BaptswapV2"}
"BaptswapV2.1" = {local = "./packages/BaptswapV2.1"}

[dev-dependencies]
